<a href="https://colab.research.google.com/github/amkathum/DRa/blob/main/LinearRegressionDay3.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

#Libraries

In [1]:
import numpy as np
import pandas as pd

#Dataset

In [2]:
!wget -O Student_Performance.zip https://www.dropbox.com/scl/fi/1lceds9y54dbjoc5eiu0u/Student_Performance.zip?rlkey=ycuxtpgeufmadx9qk4mp9e9z7&dl=0

--2026-09-13 14:45:20--  https://www.dropbox.com/scl/fi/1lceds9y54dbjoc5eiu0u/Student_Performance.zip?rlkey=ycuxtpgeufmadx9qk4mp9e9z7
Resolving www.dropbox.com (www.dropbox.com)... 162.125.3.18, 2620:100:6018:18::a27d:312
Connecting to www.dropbox.com (www.dropbox.com)|162.125.3.18|:443... connected.
HTTP request sent, awaiting response... 302 Found
Location: https://ucfe20959f50202c48d08ba82723.dl.dropboxusercontent.com/cd/0/inline/DICcK47RxnbDCNYYWPhUKDXgxY55dhZaomfOYTMCZBi0TqduznblhjIJ8Sz7KWiWC5zzpawXScSVE9Zs4QPSmIHH2sU0aa9lO87MQGFMd_lNBA5jT9AirgS_jrWPnK56YsKdKsYRN8UqAJtLQJoO92I-/file# [following]
--2026-09-13 14:45:21--  https://ucfe20959f50202c48d08ba82723.dl.dropboxusercontent.com/cd/0/inline/DICcK47RxnbDCNYYWPhUKDXgxY55dhZaomfOYTMCZBi0TqduznblhjIJ8Sz7KWiWC5zzpawXScSVE9Zs4QPSmIHH2sU0aa9lO87MQGFMd_lNBA5jT9AirgS_jrWPnK56YsKdKsYRN8UqAJtLQJoO92I-/file
Resolving ucfe20959f50202c48d08ba82723.dl.dropboxusercontent.com (ucfe20959f50202c48d08ba82723.dl.dropboxusercontent.com)... 162.125.3.15, 2620:100:6018:15::a27d:30f
Connecting to ucfe20959f50202c48d08ba82723.dl.dropboxusercontent.com (ucfe20959f50202c48d08ba82723.dl.dropboxusercontent.com)|162.125.3.15|:443... connected.
HTTP request sent, awaiting response... 302 Found
Location: /cd/0/inline2/DIDOqXStUpYj06aWp3_Wac-1jDmJ3L1P8rfqVNVQXkxuJ_HEdoJpHwikgUG2F7r_BT3-04qcb1_KIliLCQNYQiB38sNxYuZGjVEpP-_OEdbz64ZFnSAQ3xySN3hYKj9gdcJOEs-I7gLYEmr29XJQqYFG5kVJKzZslEEXgWMKQt3dWBdfS0gIx6Lnvm_Qn2O_yLZlHDZd5nTv8kLiyqD3zgPRoUOSIx58KNgOmS-REB5P9XINDF_zTznUjrDg6vzpG9UQhdztrpdrQ6unacLVK-0aJ8xwhokp0W0lB4Gt2wE1TlEG8LCaCtoyNc5VZiMVVBLGfC8Zm3fRm3Nc0-IRLpIKTjY-g-dLGmS3uZnf1hFQH95dKJgho4861aOn3LkkK2c/file [following]
--2026-09-13 14:45:22--  https://ucfe20959f50202c48d08ba82723.dl.dropboxusercontent.com/cd/0/inline2/DIDOqXStUpYj06aWp3_Wac-1jDmJ3L1P8rfqVNVQXkxuJ_HEdoJpHwikgUG2F7r_BT3-04qcb1_KIliLCQNYQiB38sNxYuZGjVEpP-_OEdbz64ZFnSAQ3xySN3hYKj9gdcJOEs-I7gLYEmr29XJQqYFG5kVJKzZslEEXgWMKQt3dWBdfS0gIx6Lnvm_Qn2O_yLZlHDZd5nTv8kLiyqD3zgPRoUOSIx58KNgOmS-REB5P9XINDF_zTznUjrDg6vzpG9UQhdztrpdrQ6unacLVK-0aJ8xwhokp0W0lB4Gt2wE1TlEG8LCaCtoyNc5VZiMVVBLGfC8Zm3fRm3Nc0-IRLpIKTjY-g-dLGmS3uZnf1hFQH95dKJgho4861aOn3LkkK2c/file
Reusing existing connection to ucfe20959f50202c48d08ba82723.dl.dropboxusercontent.com:443.
HTTP request sent, awaiting response... 200 OK
Length: 49424 (48K) [application/zip]
Saving to: ‘Student_Performance.zip’

Student_Performance 100%[===================>]  48.27K  --.-KB/s    in 0.02s

2026-09-13 14:45:22 (2.22 MB/s) - ‘Student_Performance.zip’ saved [49424/49424]

In [3]:
!unzip Student_Performance.zip

Archive:  Student_Performance.zip
  inflating: Student_Performance.csv
  inflating: __MACOSX/._Student_Performance.csv

# Read data

In [4]:
data = pd.read_csv("/content/Student_Performance.csv")

In [6]:
data.head()

,Hours Studied,Previous Scores,Extracurricular Activities,Sleep Hours,Sample Question Papers Practiced,Performance Index
0,7,99,Yes,9,1,91.0
1,4,82,No,4,2,65.0
2,8,51,Yes,7,2,45.0
3,5,52,Yes,5,2,36.0
4,7,75,No,8,5,66.0

In [7]:
# change category to numbers
data["Extracurricular Activities"] = data["Extracurricular Activities"].astype("category").cat.codes

In [5]:
data.head()

,Hours Studied,Previous Scores,Extracurricular Activities,Sleep Hours,Sample Question Papers Practiced,Performance Index
0,7,99,Yes,9,1,91.0
1,4,82,No,4,2,65.0
2,8,51,Yes,7,2,45.0
3,5,52,Yes,5,2,36.0
4,7,75,No,8,5,66.0

In [9]:
data.size

60000

In [10]:
X = data.drop("Performance Index", axis = 1) # axis = 1 for column , axis = 0 for rows
y = data["Performance Index"]

In [11]:
X.head() # X1 to X5

,Hours Studied,Previous Scores,Extracurricular Activities,Sleep Hours,Sample Question Papers Practiced
0,7,99,1,9,1
1,4,82,0,4,2
2,8,51,1,7,2
3,5,52,1,5,2
4,7,75,0,8,5

In [12]:
y.head() # label

0    91.0
1    65.0
2    45.0
3    36.0
4    66.0
Name: Performance Index, dtype: float64

In [13]:
# for the bias or theta 0
ones = np.ones(X.shape[0]) # shape[0] => number of rows shape[1] => number of columns

In [14]:
# numpy must have numpy arrays inside a tuple (nparr1,nparr2)
X = np.column_stack((ones,X.to_numpy()))

In [15]:
X

array([[ 1.,  7., 99.,  1.,  9.,  1.],
       [ 1.,  4., 82.,  0.,  4.,  2.],
       [ 1.,  8., 51.,  1.,  7.,  2.],
       ...,
       [ 1.,  6., 83.,  1.,  8.,  5.],
       [ 1.,  9., 97.,  1.,  7.,  0.],
       [ 1.,  7., 74.,  0.,  8.,  1.]])

In [16]:
# Split
from sklearn.model_selection import train_test_split
# split data 80% 20% => 80% for train , 20% for test

# X, test_size = 0.2 aka 20% => 0.8 * X , 0.2 * X
# if X had 10,000 => 8000 , 2000
# if y had 10,000 => 8000 , 2000
X_train, X_test, y_train, y_test = train_test_split(X,y,test_size = 0.2)

# Find theta

In [17]:
# only use training !
theta = np.linalg.solve(X_train.T @ X_train, X_train.T @ y_train)

In [18]:
theta

array([-34.10237096,   2.85777578,   1.01871219,   0.59865495,
         0.47661629,   0.19534952])

In [19]:
# dot product
predictions = X_test @ theta

In [20]:
features = np.array([1,9,100,0,10,1])

In [21]:
# y = C+ D t => y = theta + theta * X + theta * X
# y = m*x+b
features.T @ theta

np.float64(98.45034255855364)

In [24]:
predictions

array([56.22767146, 94.36766254, 46.67657332, ..., 69.95912941,
       31.92304326, 32.04780057])

In [25]:
# mean square erro
def mean_square_error(y_true,y_pred):

  error = y_true - y_pred

  squared_error = error **2

  mse = squared_error.mean()

  return mse

In [27]:
'''
  if mse for train and test near each other it is good
  if not, might be overfitting
'''
mean_square_error(predictions,y_test)

np.float64(3.9591370841366484)

In [28]:
mean_square_error(X_train @ theta, y_train)

np.float64(4.199871060443156)

# Sklearn

In [29]:
# import
from sklearn.linear_model import LinearRegression

In [30]:
# train
reg = LinearRegression().fit(X_train,y_train)
# predict
reg.predict(X_test)

array([56.22767146, 94.36766254, 46.67657332, ..., 69.95912941,
       31.92304326, 32.04780057])

In [31]:
reg.coef_

array([0.        , 2.85777578, 1.01871219, 0.59865495, 0.47661629,
       0.19534952])

In [32]:
print(reg.score(X_train,y_train))

0.9884777765820486

In [33]:
print(reg.score(X_test,y_test))

0.9897663968576016

In [34]:
mean_square_error(reg.predict(X_test),y_test)

np.float64(3.9591370841366462)

In [35]:
mean_square_error(reg.predict(X_train),y_train)

np.float64(4.199871060443157)